name: Build NovaDumper DLL

on:
  push:
    branches:
      - main
      - master
  pull_request:
    branches:
      - main
      - master

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4

    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@v2

    - name: Build Project to Release x64
      # *.sln kullanarak klasördeki çözüm dosyasını otomatik bulmasını sağlıyoruz
      run: msbuild *.sln /p:Configuration=Release /p:Platform=x64 /p:WarningLevel=0

    - name: Upload NovaDumper Artifact
      uses: actions/upload-artifact@v4
      with:
        name: NovaDumper_x64-Release
        path: |
          **/Release/*.dll
          
